CREATE TABLE IF NOT EXISTS `shops` (
    shopId   INT PRIMARY KEY AUTO_INCREMENT,
    shopName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `products` (
    productId   INT PRIMARY KEY AUTO_INCREMENT,
    shopId      INT NOT NULL,
    FOREIGN KEY (shopId) REFERENCES shops(shopId),
    productName VARCHAR(255) NOT NULL
);
