// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Order struct {
	Orderid int32
	Userid  int32
}

type Product struct {
	ID    int32
	Name  string
	Price string
}
