# .air.toml

# Directory watch
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -gcflags='all=-N -l' -buildvcs=false -o app ./cmd/server/main.go"
  bin = "app"
  include_ext = ["go", "tpl", "tmpl", "html"]

[log]
  time = true

[color]
  main = "cyan"
  watcher = "magenta"
  build = "yellow"
  runner = "green"